# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: Release - Build Docker image

on:
  release:
    types: [ published ]
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to build (e.g., v1.0.0)'
        required: true
        type: string

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      - name: Process version
        id: version
        run: |
          TAG="${{ github.event.inputs.tag }}"
          VERSION="${TAG#v}"  # Remove 'v' prefix
          
          # Check if this is a release version (no -test, -rc, -alpha, -beta, etc.)
          if [[ $VERSION =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
          echo "is_release=true" >> $GITHUB_OUTPUT
          echo "This is a release version"
          else
          echo "is_release=false" >> $GITHUB_OUTPUT
          echo "This is not a release version"
          fi
          
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Selected tag: $TAG"
          echo "Processed version: $VERSION"

      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.tag }}

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3.8.0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.3.0

      - name: Log in to Docker Hub
        uses: docker/login-action@v3.3.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Log in to GHCR
        uses: docker/login-action@v3.3.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for release version
        id: meta_release
        if: steps.version.outputs.is_release == 'true'
        uses: docker/metadata-action@v5.6.1
        with:
          images: vitorvasc/docker-habbo-server
          tags: |
            type=raw,value=${{ steps.version.outputs.version }}
            type=raw,value=latest

      - name: Extract metadata for non-release version
        id: meta_test
        if: steps.version.outputs.is_release == 'false'
        uses: docker/metadata-action@v5.6.1
        with:
          images: vitorvasc/docker-habbo-server
          tags: |
            type=raw,value=${{ steps.version.outputs.version }}

      - name: Build and push release Docker image
        id: push_release
        if: steps.version.outputs.is_release == 'true'
        uses: docker/build-push-action@v6.13.0
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta_release.outputs.tags }}
          labels: ${{ steps.meta_release.outputs.labels }}

      - name: Build and push non-release Docker image
        id: push_test
        if: steps.version.outputs.is_release == 'false'
        uses: docker/build-push-action@v6.13.0
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta_test.outputs.tags }}
          labels: ${{ steps.meta_test.outputs.labels }}